### ISSUE TITLE
qemu: Allow multiple instances running at the same time

### ISSUE THREAD

**Issue by HanaaAbbas** [cloudius-systems/capstan#190] opened 2021-09-27 10:36 UTC
capstan does not allow running multiple instances of the same image

capstan run -v -i image_name --boot default -n "bridge" -c 4 -m 1200M --execute "--ip=eth0,192.168.122.100,255.255.255.0 --defaultgw=192.168.122.1 --nameserver=192.168.122.1 /java.so -Xmx800m -Xss228k -jar /Jar.jar; /cli/cli.so" instance1

capstan run -v -i image_name --boot default -n "bridge" -c 2 -m 1200M --execute "--ip=eth0,192.168.122.100,255.255.255.0 --defaultgw=192.168.122.1 --nameserver=192.168.122.1 /java.so -Xmx800m -Xss228k -jar /Jar.jar; /cli/cli.so" instance2

For the second instance, this is the error I get:

Invoking QEMU at: /usr/bin/qemu-system-x86_64 with arguments:
  -vnc :1
  -m 1200
  -smp 2
  -device virtio-blk-pci,id=blk0,bootindex=0,drive=hd0
  -drive file=/home/hanaa/.capstan/instances/qemu/unicure-cc/disk.qcow2,if=none,id=hd0,aio=threads,cache=none
  -chardev stdio,mux=on,id=stdio,signal=off
  -device isa-serial,chardev=stdio
  -netdev bridge,id=hn0,br=virbr0,helper=/usr/lib/qemu/qemu-bridge-helper
  -device virtio-net-pci,netdev=hn0,id=nic1,mac=66:ee:f3:ef:04:ba
  -chardev socket,id=charmonitor,path=/home/hanaa/.capstan/instances/qemu/unicure-cc/osv.monitor,server,nowait
  -mon chardev=charmonitor,id=monitor,mode=control
qemu-system-x86_64: -vnc :1: Failed to find an available port: Address already in use

I can see in this commit af4975271e716388c42cf712ebb650b60874aaa2 
-vcn :1 was added again to the VM arguments

How can I get rid of the -vcn arg? Or how can I change the instance port?

Adding --novnc --nogdb within the osv command line (execute arg) did not help either

Thank you

**Comment by wkozaczuk** [comment] 2021-10-01 16:57
It looks like capstan does not support running multiple OSv instances on QEMU on the same host. The commit you are referring to, changed capstan verbose behavior to display full QEMU command line which was intended for situations like this to allow executing it directly from the command line and bypass capstan.

Please note that the order of instance name (instance1/2) in the context of options matters and it should be first (the help is misleading and should be fixed). So you should execute it like this:
```
capstan run instance1 -v -i image_name --boot default -n "bridge" -c 4 -m 1200M \
--execute "--ip=eth0,192.168.122.100,255.255.255.0 --defaultgw=192.168.122.1 --nameserver=192.168.122.1 /java.so -Xmx800m -Xss228k -jar /Jar.jar; /cli/cli.so"
```

In my example you see this:
```
capstan run rust-httpserver1 -i test-rust-httpserver-rofs -v -f "3001:3000"
Removing orphaned instance folder: /home/wkozaczuk/.capstan/instances/qemu/test-rust-httpserver-rofs
Command line will be set to default boot
Created instance: rust-httpserver1
Setting cmdline: runscript /run/default;
Invoking QEMU at: /usr/bin/qemu-system-x86_64 with arguments:
  -vnc :1
  -m 1024
  -smp 2
  -device virtio-blk-pci,id=blk0,bootindex=0,drive=hd0
  -drive file=/home/wkozaczuk/.capstan/instances/qemu/rust-httpserver1/disk.qcow2,if=none,id=hd0,aio=threads,cache=none
  -chardev stdio,mux=on,id=stdio,signal=off
  -device isa-serial,chardev=stdio
  -netdev user,id=un0,net=192.168.122.0/24,host=192.168.122.1,hostfwd=tcp::3001-:3000
  -device virtio-net-pci,netdev=un0
  -chardev socket,id=charmonitor,path=/home/wkozaczuk/.capstan/instances/qemu/rust-httpserver1/osv.monitor,server,nowait
  -mon chardev=charmonitor,id=monitor,mode=control
  -enable-kvm
  -cpu host,+x2apic
OSv v0.54.0-161-gcfd3d97e
eth0: 192.168.122.15
Booted up in 138.35 ms
Cmdline: runscript /run/default;
runscript expand fn='/run/default' line=0 '/libhttpserver.so'
Starting http server to listen on port 3000 ...
```

This should correctly make capstan generate a unique backing file for the drive (see option `-drive` and relevant code in capstan - https://github.com/cloudius-systems/capstan/blob/05eaaf11f0dafe33842d99e20ab70fa7ed738c90/hypervisor/qemu/qemu.go#L155-L171) and unique chardev option file.

To address the vnc option you have an option on executing the output QEMU command directly and change `-vnc :1` to `-vnc :2` or use UNIX domain socket like so: `-vnc unix:~/.qemu-myvm-vnc2`. I think changing capstan to use something like `-vnc unix:~/.capstan/instances/qemu/rust-httpserver1/qemu-vnc` would work best.

I will try to come up with a pull request and address this capstan limitation. Or if you have golang experience we would welcome it two.

**Comment by wkozaczuk** [comment] 2021-10-01 19:58
Hey, I have just pushed a commit - b41850c255093b28cbcf54392c71dcbf325d9bce - that changes capstan to use UNIX domain socket when running OSv on QEMU with vnc. I think that should allow running multiple instances of OSv on the same host.
BTW I was wrong when suggesting different order - I was using the old version of capstan which used an older library to parse arguments. So the correct way is as such (instance name at the end):
```
capstan run -i test-rust-httpserver-rofs -v -f "3001:3000" rust-httpserver1reset
Removing orphaned instance folder: /home/wkozaczuk/.capstan/instances/qemu/rust-httpserver1reset
Command line will be set to default boot
Created instance: rust-httpserver1reset
Setting cmdline: runscript /run/default;
Invoking QEMU at: /usr/bin/qemu-system-x86_64 with arguments:
  -vnc unix:/home/wkozaczuk/.capstan/instances/qemu/rust-httpserver1reset/vnc-domain-socket
  -m 1024
  -smp 2
  -device virtio-blk-pci,id=blk0,bootindex=0,drive=hd0
  -drive file=/home/wkozaczuk/.capstan/instances/qemu/rust-httpserver1reset/disk.qcow2,if=none,id=hd0,aio=threads,cache=none
  -chardev stdio,mux=on,id=stdio,signal=off
  -device isa-serial,chardev=stdio
  -netdev user,id=un0,net=192.168.122.0/24,host=192.168.122.1,hostfwd=tcp::3001-:3000
  -device virtio-net-pci,netdev=un0
  -chardev socket,id=charmonitor,path=/home/wkozaczuk/.capstan/instances/qemu/rust-httpserver1reset/osv.monitor,server,nowait
  -mon chardev=charmonitor,id=monitor,mode=control
  -enable-kvm
  -cpu host,+x2apic
OSv v0.54.0-161-gcfd3d97e
eth0: 192.168.122.15
Booted up in 138.02 ms
Cmdline: runscript /run/default;
runscript expand fn='/run/default' line=0 '/libhttpserver.so'
Starting http server to listen on port 3000 ...
```

Could you please verify if this change helps? You would have to build capstan from sources as I have not drafted new release which would have new binaries.

**Comment by HanaaAbbas** [comment] 2021-10-03 09:47
Yes thank you very much, now I can run two instances on the same host. 

@wkozaczuk I have other questions, please. I am new to OSv and my networking knowledge is still limited. 

I can see from the logs that the `Rest API server running on port 8000`.  But, how can I access the REST API via command line and/or browser?
When I run  `curl http://192.168.0.189:8000/os/version` I get no response. 

I am running OSv on Ubuntu 20.04 on VirtualBox machine. (I cannot get OSv instances running on separate virtualbox VMs to communicate between each other)

**Capstan Run** 
```
$ capstan run -v -i image -c 4 -m 1200M -n "bridge" --execute "--verbose --ip=eth0,192.168.0.189,255.255.255.0 --defaultgw=192.168.0.1 --nameserver=192.168.0.1 /java.so -Xmx800m -Xss228k -jar /Jar.jar;" instance1 
Command line will be set based on --run parameter
Created instance: instance1
Setting cmdline: --verbose --ip=eth0,192.168.0.189,255.255.255.0 --defaultgw=192.168.0.1 --nameserver=192.168.0.1 /java.so -Xmx800m -Xss228k -jar /Jar.jar 
Invoking QEMU at: /usr/bin/qemu-system-x86_64 with arguments:
  -vnc unix:/home/hanaa/.capstan/instances/qemu/unicure-cc/vnc-domain-socket
  -m 1200
  -smp 4
  -device virtio-blk-pci,id=blk0,bootindex=0,drive=hd0
  -drive file=/home/hanaa/.capstan/instances/qemu/unicure-cc/disk.qcow2,if=none,id=hd0,aio=threads,cache=none
  -chardev stdio,mux=on,id=stdio,signal=off
  -device isa-serial,chardev=stdio
  -netdev bridge,id=hn0,br=virbr0,helper=/usr/lib/qemu/qemu-bridge-helper
  -device virtio-net-pci,netdev=hn0,id=nic1,mac=c2:75:9f:fb:b3:40
  -chardev socket,id=charmonitor,path=/home/hanaa/.capstan/instances/qemu/unicure-cc/osv.monitor,server,nowait
  -mon chardev=charmonitor,id=monitor,mode=control
OSv v0.56.0
4 CPUs detected
Firmware vendor: SeaBIOS
bsd: initializing - done
VFS: mounting ramfs at /
VFS: mounting devfs at /dev
net: initializing - done
vga: Add VGA device instance
eth0: ethernet address: c2:75:9f:fb:b3:40
virtio-blk: Add blk device instances 0 as vblk0, devsize=10737418240
Warning: No hardware source of entropy available to your platform,
	CSPRNG will rely on software source of entropy to provide high-quality randomness.
random: <Software, Yarrow> initialized
VFS: unmounting /dev
VFS: mounting rofs at /rofs
failed to mount /rofs, error = No error information
VFS: mounting virtiofs at /virtiofs
[virtiofs] Error opening device!
failed to mount /virtiofs, error = No such device or address
VFS: mounting zfs at /zfs
zfs: mounting osv/zfs from device /dev/vblk0.1
random: device unblocked.
VFS: mounting devfs at /dev
VFS: mounting procfs at /proc
VFS: mounting sysfs at /sys
BSD shrinker: event handler list found: 0xffffa00000f5e280
	BSD shrinker found: 1
BSD shrinker: unlocked, running
eth0: 192.168.0.189
Booted up in 0.00 ms
Cmdline: /java.so -Xmx800m -Xss228k -jar /Jar.jar
Running from /init/30-auto-03: /libhttpserver-api.so &!
java.so: Starting JVM app using: io/osv/nonisolated/RunNonIsolatedJvmApp
httpserver: loaded plugin from path: /usr/mgmt/plugins/libhttpserver-api_trace.so
/usr/lib/jvm/jdk-zulu11.50.19-ca-jdk11.0.12-linux_x64/lib/server/libjvm.so: ignoring missing symbol mallinfo
/usr/lib/jvm/jdk-zulu11.50.19-ca-jdk11.0.12-linux_x64/lib/server/libjvm.so: ignoring missing symbol fma
/usr/lib/jvm/jdk-zulu11.50.19-ca-jdk11.0.12-linux_x64/lib/server/libjvm.so: ignoring missing symbol getutxent
/usr/lib/jvm/jdk-zulu11.50.19-ca-jdk11.0.12-linux_x64/lib/server/libjvm.so: ignoring missing symbol setutxent
java.so: Setting Java system classloader to NonIsolatingOsvSystemClassLoader
httpserver: loaded plugin from path: /usr/mgmt/plugins/libhttpserver-api_os.so
httpserver: loaded plugin from path: /usr/mgmt/plugins/libhttpserver-api_fs.so
httpserver: loaded plugin from path: /usr/mgmt/plugins/libhttpserver-api_app.so
httpserver: loaded plugin from path: /usr/mgmt/plugins/libhttpserver-api_file.so
httpserver: loaded plugin from path: /usr/mgmt/plugins/libhttpserver-api_hardware.so
/usr/lib/jvm/jdk-zulu11.50.19-ca-jdk11.0.12-linux_x64/lib/libjava.so: ignoring missing symbol posix_spawn
/usr/lib/jvm/jdk-zulu11.50.19-ca-jdk11.0.12-linux_x64/lib/libjava.so: ignoring missing symbol waitid
httpserver: loaded plugin from path: /usr/mgmt/plugins/libhttpserver-api_env.so
httpserver: loaded plugin from path: /usr/mgmt/plugins/libhttpserver-api_network.so
httpserver: loaded plugin from path: /usr/mgmt/plugins/libhttpserver-api_api.so
Rest API server running on port 8000
```

This is my **package.yaml**
```
name: project
title: project_title
author: Anonymous
version: 1.0.0
require:
- osv.openjdk11-zulu
- osv.run-java
- osv.cli
- osv.httpserver-html5-gui-and-cli
created: "2021-09-26T01:12:24+03:00"
```

Thank you so much, 
I really appreciate your help!

**Comment by robo3945** [comment] 2021-10-06 06:33
Hi everbody, is there any advice about this? It is interesting for me too

**Closed** 2021-10-06 23:52 UTC
